### ISSUE TITLE
libmapper no longer uses the `Calibrating` property.

### ISSUE THREAD

**Issue by peacheym** [lemurph/IOMapper#8]
Commit `004aa8085c9fdfe57a64c98bc0278cb931ef07c1` in the libmapper repo (see [here](https://github.com/libmapper/libmapper/commit/004aa8085c9fdfe57a64c98bc0278cb931ef07c1)) removes the `Calibrating` property. 

When attempting to build IOMapper with `scons`, the following error gets returned. 

```
[ 38%] In file included from modules/IOMapper/register_types.cpp:6:
modules/IOMapper/IOMapper.h:38:58: error: 'CALIBRATING' is not a member of 'mapper::Property'
   38 |             CALIBRATING         = (int)mapper::Property::CALIBRATING,
```

Which leads me to believe that IOMapper is still looking to use the Calibrating property, despite it being removed from libmapper. I'll see if I can start up a PR to fix this! 😄

**Comment by lemurph** [comment]
Removed "CALIBRATING" from IOMapper.cpp and IOMapper.h
